package rules

import java.util.List

import com.sample.droolsissue.models.Product
import com.sample.droolsissue.models.OrderLine

global List<Product> discountProducts

rule "discount product if id or category is included in the discount list"

    when
		$orderLine: OrderLine()

		Product(
			id == $orderLine.product.id || category == $orderLine.product.category
		) from discountProducts

    then
		System.out.println(drools.getRule().getName());

end
