package rules

import java.util.List

import com.sample.droolsissue.models.Product
import com.sample.droolsissue.models.OrderLine

global List<Product> discountProducts

rule "discount product if id or category is included in the discount list(use bound variable for id)"

    when
		$orderLine: OrderLine($product: product)

		Product(
			id == $product.id || category == $orderLine.product.category
		) from discountProducts

    then
		System.out.println(drools.getRule().getName());

end

rule "discount product if id or category is included in the discount list(use bound variable for category)"

    when
		$orderLine: OrderLine($product: product)

		Product(
			id == $orderLine.product.id || category == $product.category
		) from discountProducts

    then
		System.out.println(drools.getRule().getName());

end

rule "discount product if product id is in the discount list"

    when
		$orderLine: OrderLine()

		Product(
			id == $orderLine.product.id
		) from discountProducts

    then
		System.out.println(drools.getRule().getName());

end

rule "discount order if category is included in the discount list"

    when
		$orderLine: OrderLine()

		Product(
			category == $orderLine.product.category
		) from discountProducts

    then
		System.out.println(drools.getRule().getName());

end

